-- Script de inicializacao do banco de dados
-- Executado automaticamente quando o MySQL sobe pela primeira vez
-- As tabelas sao criadas pelo Hibernate (ddl-auto)
-- Usuarios podem se registrar pela interface em /login.html
